[package]
name = "casync-http"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
casync-format = { path = "../format" }
failure = "0.1"
reqwest = "0.9"
tempfile-fast = "0.3"
