[package]
name = "casync-http"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
casync-format = { path = "../format" }
error-chain = "0.10.0"
reqwest = "0.7.3"
tempfile-fast = "0.1.1"
