[package]
name = "casync-tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
casync-format = { path = "../format" }
clap = "2"
error-chain = "0.12"
