[package]
name = "casync-format"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
license = "MIT OR Apache-2.0"

edition = "2018"

[dependencies]
failure = "0.1"
sha2 = "0.8"
zstd = "0.5"
